* Abrir jupyter sin necesidad de anaconda
* CMD para abrir anaconda
    * Escritorio
    * Ubicación real
* Extension de archivos en python
    * py
    * ipynb
* copiar y clonar el repositorio a su pc

* Librerias para machine learning <br>
(en la carpeta documentación se peude encontrar algunos ejemplos de cada libreria)
    * Matplotlib
    * Numpy
    * Pandas


* Que es la inteligencia artificial? <br>
https://www.youtube.com/watch?v=i1wGMQ3TjzA&list=PL-Ogd76BhmcDxef4liOGXGXLL-4h65bs4 (20 videos)
* Mahcine learning
    * regresion

    * Clasificacion


<img src=https://i.ytimg.com/vi/SsFBnvkoZa4/maxresdefault.jpg>
<img src=http://contenidosdigitales.ulp.edu.ar/exe/matematica_NEE/Clasificacion_de_cuerpos_1.png>

<img src="./clases_anteriores/imagenes_clase_4/proceso.png">

# Sesion 2 
comandos en cmd para copiar
* cp
* mkdir
## ejercicios en python
* ejercicios para python http://aprendeconalf.es/python/ejercicios/

In [1]:
# x='hola mundo'
y=1
if y==1:
    x='hola mundo'
else:
    z='hola mundo'
try:
    print(x)
except NameError:
    print('la condicion no se cumplió')

hola mundo


In [2]:
x=range(6)
print(x)

animales=['perro','gato','loro','caballo']
animales[0]

range(0, 6)


'perro'

In [3]:
for numeros in range(4):
    print(animales[numeros])

perro
gato
loro
caballo


In [4]:
import numpy as np

In [12]:
var=np.array([[[2,3,4],[5,6,7]],[[8,9,10],[11,12,13]]])
print(var)
print(var.shape)
rand=np.random.random([2,2])

[[[ 2  3  4]
  [ 5  6  7]]

 [[ 8  9 10]
  [11 12 13]]]
(2, 2, 3)


In [21]:
m1=np.array([[1,2,3],[4,5,6],[7,8,9]])

m2=np.random.random([3,3])

m3=np.eye(3,3)

print('{} \n \n {} \n \n {} \n \n '.format(m1,m2,m3))
print(np.dot(m1,m2))

print('\n \n')
print(np.dot(m3,m2))

[[1 2 3]
 [4 5 6]
 [7 8 9]] 
 
 [[0.75914124 0.39331789 0.67600553]
 [0.14892341 0.42415762 0.4973936 ]
 [0.23177887 0.13042714 0.35941947]] 
 
 [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]] 
 
 
[[ 1.75232468  1.63291454  2.74905114]
 [ 5.17185525  4.47662247  7.34750694]
 [ 8.59138582  7.32033041 11.94596274]]

 

[[0.75914124 0.39331789 0.67600553]
 [0.14892341 0.42415762 0.4973936 ]
 [0.23177887 0.13042714 0.35941947]]


In [27]:
np.linspace(0,100,101)
np.arange(0,101,1)

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100])

In [37]:
def cambiar_forma(matriz)
    return matriz_organizada

m1=np.array([[1,2,3,4,5,6,7,8,1],[7,9,4,7,3,7,5,8,9]])
# m1.reshape(9,1)
cambiar_forma(m1)

ValueError: cannot reshape array of size 18 into shape (1,16)