# Comandos Numpy
numpy permite realiar operaciones con matrices logrando menor peso en sus variables y obteneindo mayor rapidez para realizar los calculos.

In [1]:
import numpy as np

In [24]:
#crear una matriz 1D
m1=np.array([1,1])
#crear una matriz 2D
m2=np.array([[1,1],[2,2]])
#crear una matriz 3D
m3=np.array([[[1,1],[2,2]],[[1,1],[2,2]]])
print('matriz en 1D: \n{}'.format(m1))
print('matriz en 2D: \n{}'.format(m2))
print('matriz en 3D: \n{}'.format(m3))

matriz en 1D: 
[1 1]
matriz en 2D: 
[[1 1]
 [2 2]]
matriz en 3D: 
[[[1 1]
  [2 2]]

 [[1 1]
  [2 2]]]


In [34]:
#las matrices en numpy tiene un tipo especial en pyton 
print(type(m2))
# para saber el tipo de dato interno, se utiliza el metodo .dtype
print(m2.dtype)

<class 'numpy.ndarray'>
int32


In [113]:
#crear matriz de unos
ones=np.ones([2,2], dtype=int)
print('matriz de unos: \n{}'.format(ones))
#crear matriz de ceros
zero=np.zeros([2,2], dtype=int)
print('matriz de ceros: \n{}'.format(zero))
#crear matriz aleatoria
rand=np.random.random([2,2])
print('matriz de numeros aleatorios: \n{}'.format(rand))
#matriz con un valor pera todos
fll=np.full([2,2],8)
print('matriz de de x valor: \n{}'.format(fll))
#matriz identidad
eye=np.eye(5,dtype=int)
print('matriz identidad: \n{}'.format(eye))

matriz de unos: 
[[1 1]
 [1 1]]
matriz de ceros: 
[[0 0]
 [0 0]]
matriz de numeros aleatorios: 
[[0.05174383 0.06680076]
 [0.46331671 0.84815922]]
matriz de de x valor: 
[[8 8]
 [8 8]]
matriz identidad: 
[[1 0 0 0 0]
 [0 1 0 0 0]
 [0 0 1 0 0]
 [0 0 0 1 0]
 [0 0 0 0 1]]


In [114]:
#vectores espaciados
np.linspace(0,2,11)#crea un vector con 11 puntos desde 0 hasta 2
np.arange(0,2.2,.2)#crea un vector desde 0 con incrementos de 0.2 hasta ser igual a 2.2 (no inluye el ultimo valor)

array([0. , 0.2, 0.4, 0.6, 0.8, 1. , 1.2, 1.4, 1.6, 1.8, 2. ])

In [133]:
#metodos para inspeccionar matrices
matriz=np.array([[1,2,3],[1,2,3]])
print(matriz)
print('cuantas dimensiones tiene la matriz: {}'.format(matriz.ndim))
print('cual es el tipo de variables en la matriz: {}'.format(matriz.dtype))
print('cualtos valores tiene la matriz: {}'.format(matriz.size))
print('cual es la dimension de la matriz: {}'.format(matriz.shape))

[[1 2 3]
 [1 2 3]]
cuantas dimensiones tiene la matriz: 2
cual es el tipo de variables en la matriz: int32
cualtos valores tiene la matriz: 6
cual es la dimension de la matriz: (2, 3)


In [158]:
#cambiar forma de la matriz
matriz=np.array([[1,2,3],[1,2,3]])
print(matriz)
print('tamaño de la matriz: {}'.format(matriz.size))
#solo se puede dimensionar una matriz siendo porporcional a su tamaño, para un tamaño de 6 se peude
#(1,6)(2,3)(3,2)
print('matriz cambiada a (1,6): \n {}'.format(matriz.reshape(1,6)))
print('Matriz cambiada a (3,2): \n {}'.format(matriz.reshape(3,2)))

[[1 2 3]
 [1 2 3]]
tamaño de la matriz: 6
matriz cambiada a (1,6): 
 [[1 2 3 1 2 3]]
Matriz cambiada a (3,2): 
 [[1 2]
 [3 1]
 [2 3]]


In [173]:
#obtener un valor especifico de una matriz
matriz=np.array([[1,2,3],[1,2,3]])
print('matriz para prueba \n{}'.format(matriz))
print('ubicacion puntual en la matriz {}'.format(matriz[1,2]))
print('obtener toda una columna {}'.format(matriz[:,1]))
print('obetener toda una fila {}'.format(matriz[1,:]))

matriz para prueba 
[[1 2 3]
 [1 2 3]]
ubicacion puntual en la matriz 3
obtener toda una columna [2 2]
obetener toda una fila [1 2 3]


In [190]:
#obtencion de valores estadisticos
matriz=np.array([[7,16,3],[4,8,1]])
print(matriz)
print('valor maximo en la matriz {}'.format(matriz.max()))
print('valor minimo en la matriz {}'.format(matriz.min()))
print('suma de todos los valores en una matriz {}'.format(matriz.sum()))
print('deasviacion estandar de una matriz {}'.format(matriz.std()))

[[ 7 16  3]
 [ 4  8  1]]
valor maximo en la matriz 16
valor minimo en la matriz 1
suma de todos los valores en una matriz 39
deasviacion estandar de una matriz 4.856267428111155


4.856267428111155

In [202]:
#operaiones con matrices
matriz_1=np.array([[7,16,3],[4,8,1]])
matriz_2=np.array([[1,2,3],[4,5,6]])
print('las matrices para las operaiones serán : \n m1:\n{} \n m2:\n{}'.format(matriz_1,matriz_2))
suma=matriz_1+matriz_2
multi=matriz_1+matriz_2
print('m1 + m2 = \n {}'.format(suma))
print('m1 * m2 = \n {}'.format(multi))
#estas operaiones se hacen en linea, apra haer operaciones matriciales como la multiplicacion, se utilizan funiones especificas de numpy
print('Raiz cuadrada de todos los elementos de una matriz = \n{}'.format(np.sqrt(matriz_1)))
matriz_2=matriz_2.reshape(3,2)#organizamos la matriz 2 para cambair su tamaño
print('producto punto de una matriz = \n {}'.format(np.dot(matriz_1,matriz_2)))

las matrices para las operaiones serán : 
 m1:
[[ 7 16  3]
 [ 4  8  1]] 
 m2:
[[1 2 3]
 [4 5 6]]
m1 + m2 = 
 [[ 8 18  6]
 [ 8 13  7]]
m1 * m2 = 
 [[ 8 18  6]
 [ 8 13  7]]
Raiz cuadrada de todos los elementos de una matriz = 
[[2.64575131 4.         1.73205081]
 [2.         2.82842712 1.        ]]
producto punto de una matriz = 
 [[70 96]
 [33 46]]
